language: swift
osx_image: xcode9
script:
  - xcodebuild clean -project Examples/Examples.xcodeproj -scheme Examples -destination "platform=iOS Simulator,name=iPhone X,OS=latest" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet